import { MemphisMark } from "@/components/MemphisMark";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { BookOpen, CalendarDays, Check, ChevronRight, CircleUserRound, Clock3, Download, FileText, GraduationCap, Handshake, Home, LayoutList, Loader2, LogOut, MapPin, Menu, PackageSearch, Plus, Search, UsersRound, X } from "lucide-react";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type HubSection = "dashboard" | "profile" | "notes" | "groups" | "timetable" | "deadlines" | "lost-found";
const sectionTitles: Record<HubSection, string> = { dashboard: "Good to see you", profile: "Your student profile", notes: "Notes library", groups: "Study circles", timetable: "Weekly timetable", deadlines: "Deadline tracker", "lost-found": "Lost & found" };
const nav = [
  { key: "dashboard" as const, label: "Dashboard", icon: Home }, { key: "profile" as const, label: "Profile", icon: CircleUserRound },
  { key: "notes" as const, label: "Notes", icon: BookOpen }, { key: "groups" as const, label: "Study groups", icon: UsersRound },
  { key: "timetable" as const, label: "Timetable", icon: CalendarDays }, { key: "deadlines" as const, label: "Deadlines", icon: LayoutList },
  { key: "lost-found" as const, label: "Lost & found", icon: PackageSearch },
];
const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] as const;
const colors: Record<string, string> = { mint: "bg-[#c6f6e7]", lilac: "bg-[#e8ddff]", yellow: "bg-[#ffe46a]", peach: "bg-[#ffc6ad]" };

function formatDate(value: Date | string) { return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
function getToday() { return new Intl.DateTimeFormat("en-US", { weekday: "long" }).format(new Date()) as (typeof days)[number]; }
function timeToMinutes(time: string) { const [h, m] = time.split(":").map(Number); return h * 60 + m; }
function readFileAsBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("We could not read that file.")); reader.onload = () => resolve(String(reader.result).split(",")[1] ?? ""); reader.readAsDataURL(file); }); }

function PageHeader({ eyebrow, title, action }: { eyebrow: string; title: string; action?: ReactNode }) {
  return <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-display text-xs font-black uppercase tracking-[.2em] text-[#6046a6]">{eyebrow}</p><h1 className="mt-2 font-display text-4xl font-black uppercase leading-none tracking-[-.045em] md:text-5xl">{title}</h1></div>{action}</div>;
}

function EmptyState({ title, text, icon: Icon }: { title: string; text: string; icon: typeof BookOpen }) {
  return <div className="rounded-2xl border-2 border-dashed border-black bg-white/50 px-6 py-12 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-xl border-2 border-black bg-[#ffe46a]"><Icon className="h-6 w-6" /></span><h3 className="mt-4 font-display text-xl font-black uppercase">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm font-medium text-black/65">{text}</p></div>;
}

function ProfileView() {
  const utils = trpc.useUtils();
  const profileQuery = trpc.hub.profile.get.useQuery();
  const save = trpc.hub.profile.save.useMutation({ onSuccess: () => { utils.hub.profile.get.invalidate(); utils.hub.dashboard.invalidate(); toast.success("Profile saved — you’re all set!"); }, onError: error => toast.error(error.message) });
  const profile = profileQuery.data;
  const [form, setForm] = useState({ fullName: "", university: "", department: "", semester: "" });
  useEffect(() => { if (profile) setForm({ fullName: profile.fullName, university: profile.university, department: profile.department, semester: profile.semester }); }, [profile]);
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate(form); };
  if (profileQuery.isLoading) return <LoadingState />;
  if (profileQuery.error) return <QueryError message={profileQuery.error.message} />;
  return <><PageHeader eyebrow="Make it yours" title="Student profile" /><form onSubmit={submit} className="grid max-w-3xl gap-5 rounded-[24px] border-2 border-black bg-white p-6 shadow-[6px_6px_0_#000] md:grid-cols-2"><Field label="Your name"><Input value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} placeholder="Ayesha Khan" required /></Field><Field label="University"><Input value={form.university} onChange={e => setForm({ ...form, university: e.target.value })} placeholder="Your university" required /></Field><Field label="Department"><Input value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} placeholder="Computer Science" required /></Field><Field label="Semester"><Input value={form.semester} onChange={e => setForm({ ...form, semester: e.target.value })} placeholder="Semester 4" required /></Field><div className="md:col-span-2"><Button className="memphis-button" disabled={save.isPending}>{save.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Save profile</Button></div></form><p className="mt-5 max-w-2xl text-sm font-medium leading-6 text-black/60">Your profile helps fellow students recognize you in study group member lists. Your university, department, and semester remain part of your student-only workspace.</p></>;
}

function DashboardView({ setSection }: { setSection: (section: HubSection) => void }) {
  const { data, isLoading } = trpc.hub.dashboard.useQuery();
  if (isLoading) return <LoadingState />;
  if (!data) return <QueryError message="We could not load your dashboard. Please refresh and try again." />;
  const today = getToday();
  const classes = (data?.timetable ?? []).filter(entry => entry.dayOfWeek === today).sort((a, b) => timeToMinutes(a.startTime) - timeToMinutes(b.startTime));
  return <><PageHeader eyebrow="Your academic home base" title={data.profile ? `Hey, ${data.profile.fullName.split(" ")[0]}!` : "Welcome, student."} action={<span className="hidden rounded-full border-2 border-black bg-[#ffe46a] px-4 py-2 text-xs font-black uppercase tracking-wide sm:inline-flex">{today}</span>} />
    {!data.profile && <div className="mb-7 flex flex-wrap items-center justify-between gap-3 rounded-2xl border-2 border-black bg-[#e8ddff] p-4 shadow-[4px_4px_0_#000]"><p className="font-bold">Complete your profile once to make your hub feel like yours.</p><Button onClick={() => setSection("profile")} className="memphis-button !px-4 !py-2">Set up profile <ChevronRight className="ml-1 h-4 w-4" /></Button></div>}
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="rounded-[24px] border-2 border-black bg-white p-5 shadow-[6px_6px_0_#000]"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-2xl font-black uppercase">Coming up</h2><Button variant="link" onClick={() => setSection("deadlines")} className="font-black text-black underline">All deadlines</Button></div>{data?.upcomingDeadlines?.length ? <div className="space-y-3">{data.upcomingDeadlines.map(deadline => <div key={deadline.id} className="flex items-center gap-3 rounded-xl border-2 border-black bg-[#fff7ef] p-3"><span className={`h-3 w-3 shrink-0 rounded-full border border-black ${deadline.priority === "high" ? "bg-[#ff8e72]" : deadline.priority === "medium" ? "bg-[#ffe46a]" : "bg-[#c6f6e7]"}`} /><div className="min-w-0 flex-1"><p className="truncate font-black">{deadline.title}</p><p className="text-xs font-semibold text-black/60">{deadline.subject} · due {formatDate(deadline.dueAt)}</p></div><Badge className="border-2 border-black bg-white text-[10px] font-black uppercase text-black">{deadline.priority}</Badge></div>)}</div> : <EmptyState title="No deadlines yet" text="Add your first assignment or exam deadline and it will show up here." icon={LayoutList} />}</section>
      <section className="rounded-[24px] border-2 border-black bg-[#c6f6e7] p-5 shadow-[6px_6px_0_#000]"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-2xl font-black uppercase">Today’s classes</h2><Clock3 className="h-5 w-5" /></div>{classes.length ? <div className="space-y-3">{classes.map(entry => <div key={entry.id} className="rounded-xl border-2 border-black bg-white/75 p-3"><p className="font-black">{entry.subject}</p><p className="mt-1 text-xs font-bold">{entry.startTime}–{entry.endTime} · {entry.room}</p></div>)}</div> : <p className="rounded-xl border-2 border-dashed border-black p-4 text-sm font-bold">Nothing on the schedule today. A small win.</p>}<Button variant="link" onClick={() => setSection("timetable")} className="mt-3 px-0 font-black text-black underline">Open timetable</Button></section></div>
    <section className="mt-6 rounded-[24px] border-2 border-black bg-[#ffe46a] p-5 shadow-[6px_6px_0_#000]"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-2xl font-black uppercase">Fresh notes</h2><p className="mt-1 text-sm font-medium">The latest material shared by your campus community.</p></div><Button onClick={() => setSection("notes")} className="memphis-button !bg-white !px-4 !py-2 !text-black">Browse notes</Button></div>{data?.recentNotes?.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.recentNotes.map(note => <div key={note.id} className="rounded-xl border-2 border-black bg-white p-4"><FileText className="mb-4 h-6 w-6" /><p className="truncate font-black">{note.title}</p><p className="mt-1 text-xs font-bold text-black/60">{note.subject} · {note.category}</p></div>)}</div> : <p className="rounded-xl border-2 border-dashed border-black p-4 text-sm font-bold">The notes library is waiting for its first upload.</p>}</section>
  </>;
}

function NotesView() {
  const utils = trpc.useUtils(); const [query, setQuery] = useState(""); const [subject, setSubject] = useState("all"); const [category, setCategory] = useState("all"); const [open, setOpen] = useState(false); const [file, setFile] = useState<File | null>(null);
  const notesQuery = trpc.hub.notes.list.useQuery({ query: query || undefined, subject: subject === "all" ? undefined : subject, category: category === "all" ? undefined : category });
  const upload = trpc.hub.notes.upload.useMutation({ onSuccess: () => { utils.hub.notes.list.invalidate(); utils.hub.dashboard.invalidate(); setOpen(false); setFile(null); toast.success("Your notes are live in the library."); }, onError: e => toast.error(e.message) });
  const subjects = Array.from(new Set((notesQuery.data ?? []).map(note => note.subject))); const categories = Array.from(new Set((notesQuery.data ?? []).map(note => note.category)));
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!file) return toast.error("Choose a note file first."); if (file.size > 8 * 1024 * 1024) return toast.error("Please choose a file smaller than 8 MB."); const form = new FormData(event.currentTarget); try { upload.mutate({ title: String(form.get("title")), subject: String(form.get("subject")), category: String(form.get("category")), description: String(form.get("description") || "") || undefined, fileName: file.name, mimeType: file.type || "text/plain", fileData: await readFileAsBase64(file) }); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to prepare this file."); } };
  return <><PageHeader eyebrow="A shared academic library" title="Notes library" action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="memphis-button"><Plus className="mr-2 h-4 w-4" />Upload notes</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto border-2 border-black sm:max-w-lg"><DialogHeader><DialogTitle className="font-display text-2xl font-black uppercase">Share a note</DialogTitle><DialogDescription>PDF, Word, or text file; up to 8 MB.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Title"><Input name="title" placeholder="Unit 3 revision notes" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Subject"><Input name="subject" placeholder="Calculus" required /></Field><Field label="Category"><Input name="category" placeholder="Lecture notes" required /></Field></div><Field label="Short description"><Textarea name="description" placeholder="What students will find inside" /></Field><Field label="File"><Input type="file" accept=".pdf,.doc,.docx,.txt,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={e => setFile(e.target.files?.[0] ?? null)} required /></Field>{file && <p className="text-xs font-bold">Selected: {file.name} · {(file.size / 1024 / 1024).toFixed(1)} MB</p>}<Button className="memphis-button w-full" disabled={upload.isPending}>{upload.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Upload to library</Button></form></DialogContent></Dialog>} />
    <div className="mb-6 grid gap-3 rounded-2xl border-2 border-black bg-white p-4 shadow-[4px_4px_0_#000] md:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4" /><Input value={query} onChange={e => setQuery(e.target.value)} className="pl-9" placeholder="Search title, subject, or description" /></div><FilterSelect value={subject} onChange={setSubject} placeholder="All subjects" options={subjects} /><FilterSelect value={category} onChange={setCategory} placeholder="All categories" options={categories} /></div>
    {notesQuery.error ? <QueryError message={notesQuery.error.message} /> : notesQuery.isLoading ? <LoadingState /> : notesQuery.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{notesQuery.data.map(note => <article key={note.id} className="rounded-2xl border-2 border-black bg-white p-5 shadow-[4px_4px_0_#000]"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border-2 border-black bg-[#e8ddff]"><FileText className="h-5 w-5" /></span><Badge className="border-2 border-black bg-[#ffe46a] text-[10px] font-black uppercase text-black">{note.category}</Badge></div><h2 className="mt-5 line-clamp-2 font-display text-xl font-black uppercase leading-none">{note.title}</h2><p className="mt-2 text-sm font-bold text-[#6046a6]">{note.subject}</p>{note.description && <p className="mt-3 line-clamp-2 text-sm font-medium leading-5 text-black/65">{note.description}</p>}<div className="mt-5 flex items-center justify-between border-t-2 border-black pt-4 text-xs font-bold"><span>{(note.fileSize / 1024 / 1024).toFixed(1)} MB</span><a href={note.fileUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-black underline"><Download className="h-4 w-4" />Download</a></div></article>)}</div> : <EmptyState title="No matching notes" text="Try a different search or upload the first resource for this subject." icon={BookOpen} />}</>;
}

function GroupsView() {
  const utils = trpc.useUtils(); const [query, setQuery] = useState(""); const [subject, setSubject] = useState("all"); const [open, setOpen] = useState(false); const [memberGroupId, setMemberGroupId] = useState<number | null>(null);
  const groupsQuery = trpc.hub.groups.list.useQuery({ query: query || undefined, subject: subject === "all" ? undefined : subject }); const membersQuery = trpc.hub.groups.members.useQuery({ groupId: memberGroupId ?? 0 }, { enabled: Boolean(memberGroupId) });
  const create = trpc.hub.groups.create.useMutation({ onSuccess: () => { utils.hub.groups.list.invalidate(); setOpen(false); toast.success("Study group created — you’re the first member."); }, onError: e => toast.error(e.message) }); const join = trpc.hub.groups.join.useMutation({ onSuccess: () => { utils.hub.groups.list.invalidate(); toast.success("You joined the study group."); }, onError: e => toast.error(e.message) });
  const subjects = Array.from(new Set((groupsQuery.data ?? []).map(group => group.subject))); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ name: String(form.get("name")), subject: String(form.get("subject")), description: String(form.get("description")), memberLimit: Number(form.get("memberLimit")) || 12 }); };
  return <><PageHeader eyebrow="Find your people" title="Study circles" action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="memphis-button"><Plus className="mr-2 h-4 w-4" />Create a group</Button></DialogTrigger><DialogContent className="border-2 border-black sm:max-w-lg"><DialogHeader><DialogTitle className="font-display text-2xl font-black uppercase">Start a study circle</DialogTitle><DialogDescription>Set the subject, focus, and a comfortable member limit.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Group name"><Input name="name" placeholder="Algorithms sprint club" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Subject"><Input name="subject" placeholder="Algorithms" required /></Field><Field label="Member limit"><Input name="memberLimit" type="number" min="2" max="100" defaultValue="12" required /></Field></div><Field label="What will you work on?"><Textarea name="description" placeholder="Weekly revision, practice problems, or exam prep" required /></Field><Button className="memphis-button w-full" disabled={create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Create study circle</Button></form></DialogContent></Dialog>} />
    <div className="mb-6 grid gap-3 rounded-2xl border-2 border-black bg-white p-4 shadow-[4px_4px_0_#000] md:grid-cols-[1fr_220px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4" /><Input value={query} onChange={e => setQuery(e.target.value)} className="pl-9" placeholder="Search group name, subject, or focus" /></div><FilterSelect value={subject} onChange={setSubject} placeholder="All subjects" options={subjects} /></div>
    {groupsQuery.error ? <QueryError message={groupsQuery.error.message} /> : groupsQuery.isLoading ? <LoadingState /> : groupsQuery.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{groupsQuery.data.map(group => <article key={group.id} className="rounded-2xl border-2 border-black bg-white p-5 shadow-[4px_4px_0_#000]"><div className="flex justify-between gap-3"><Badge className="border-2 border-black bg-[#c6f6e7] text-[10px] font-black uppercase text-black">{group.subject}</Badge><span className="text-xs font-black">{group.memberCount}/{group.memberLimit}</span></div><h2 className="mt-5 font-display text-xl font-black uppercase leading-none">{group.name}</h2><p className="mt-3 line-clamp-3 text-sm font-medium leading-5 text-black/70">{group.description}</p><div className="mt-5 flex flex-wrap gap-2 border-t-2 border-black pt-4"><Button variant="outline" onClick={() => setMemberGroupId(group.id)} className="border-2 border-black bg-white font-black">Members</Button>{group.isMember ? <span className="inline-flex items-center gap-1 rounded-md border-2 border-black bg-[#c6f6e7] px-3 py-2 text-xs font-black"><Check className="h-3 w-3" />Joined</span> : <Button onClick={() => join.mutate({ groupId: group.id })} className="memphis-button !px-3 !py-2" disabled={join.isPending || group.memberCount >= group.memberLimit}>Join</Button>}</div></article>)}</div> : <EmptyState title="No study circles found" text="Create the first group for your subject or broaden your search." icon={UsersRound} />}
    <Dialog open={Boolean(memberGroupId)} onOpenChange={open => !open && setMemberGroupId(null)}><DialogContent className="border-2 border-black sm:max-w-md"><DialogHeader><DialogTitle className="font-display text-2xl font-black uppercase">Group members</DialogTitle><DialogDescription>Students currently in this study circle.</DialogDescription></DialogHeader>{membersQuery.isLoading ? <LoadingState /> : <div className="space-y-3">{membersQuery.data?.map(member => <div key={member.userId} className="flex items-center gap-3 rounded-xl border-2 border-black bg-[#fff7ef] p-3"><Avatar className="border-2 border-black"><AvatarFallback className="bg-[#ffe46a] font-black">{member.fullName?.[0] ?? "S"}</AvatarFallback></Avatar><div><p className="font-black">{member.fullName ?? "Student"}</p><p className="text-xs font-semibold text-black/60">{member.department ?? "Student"} · {member.semester ?? "—"}</p></div></div>)}</div>}</DialogContent></Dialog>
  </>;
}

function TimetableView() {
  const utils = trpc.useUtils(); const [open, setOpen] = useState(false); const list = trpc.hub.timetable.list.useQuery(); const create = trpc.hub.timetable.create.useMutation({ onSuccess: () => { utils.hub.timetable.list.invalidate(); utils.hub.dashboard.invalidate(); setOpen(false); toast.success("Class added to your timetable."); }, onError: e => toast.error(e.message) }); const remove = trpc.hub.timetable.remove.useMutation({ onSuccess: () => { utils.hub.timetable.list.invalidate(); utils.hub.dashboard.invalidate(); toast.success("Class removed."); }, onError: e => toast.error(e.message) });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const startTime = String(form.get("startTime")); const endTime = String(form.get("endTime")); if (timeToMinutes(endTime) <= timeToMinutes(startTime)) return toast.error("End time must be later than start time."); create.mutate({ dayOfWeek: String(form.get("dayOfWeek")) as (typeof days)[number], startTime, endTime, subject: String(form.get("subject")), room: String(form.get("room")), color: String(form.get("color")) as "mint" | "lilac" | "yellow" | "peach" }); };
  return <><PageHeader eyebrow="Build a better week" title="Weekly timetable" action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="memphis-button"><Plus className="mr-2 h-4 w-4" />Add class</Button></DialogTrigger><DialogContent className="border-2 border-black sm:max-w-lg"><DialogHeader><DialogTitle className="font-display text-2xl font-black uppercase">Add a class</DialogTitle><DialogDescription>Keep the time, subject, and room in one easy-to-scan week.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Day"><NativeSelect name="dayOfWeek" options={days} /></Field><Field label="Colour"><NativeSelect name="color" options={["mint", "lilac", "yellow", "peach"]} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Start time"><Input name="startTime" type="time" required /></Field><Field label="End time"><Input name="endTime" type="time" required /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Subject"><Input name="subject" placeholder="Data Structures" required /></Field><Field label="Room"><Input name="room" placeholder="B-204" required /></Field></div><Button className="memphis-button w-full" disabled={create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Add to timetable</Button></form></DialogContent></Dialog>} />
    {list.error ? <QueryError message={list.error.message} /> : list.isLoading ? <LoadingState /> : <div className="grid gap-4 xl:grid-cols-2">{days.map(day => { const entries = (list.data ?? []).filter(item => item.dayOfWeek === day).sort((a, b) => timeToMinutes(a.startTime) - timeToMinutes(b.startTime)); return <section key={day} className={`rounded-2xl border-2 border-black p-5 shadow-[4px_4px_0_#000] ${day === getToday() ? "bg-[#ffe46a]" : "bg-white"}`}><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl font-black uppercase">{day}</h2>{day === getToday() && <Badge className="border-2 border-black bg-white text-[10px] font-black uppercase text-black">Today</Badge>}</div>{entries.length ? <div className="space-y-3">{entries.map(entry => <div key={entry.id} className={`flex items-center gap-3 rounded-xl border-2 border-black p-3 ${colors[entry.color] ?? colors.mint}`}><div className="min-w-0 flex-1"><p className="font-black">{entry.subject}</p><p className="text-xs font-bold">{entry.startTime}–{entry.endTime} · {entry.room}</p></div><button aria-label={`Remove ${entry.subject}`} onClick={() => remove.mutate({ entryId: entry.id })} className="rounded-md border-2 border-black bg-white p-1.5"><X className="h-4 w-4" /></button></div>)}</div> : <p className="text-sm font-bold text-black/55">Open space for now.</p>}</section>; })}</div>}</>;
}

function DeadlinesView() {
  const utils = trpc.useUtils(); const [status, setStatus] = useState<"pending" | "completed">("pending"); const [priorityFilter, setPriorityFilter] = useState("all"); const [open, setOpen] = useState(false); const list = trpc.hub.deadlines.list.useQuery({ status, priority: priorityFilter === "all" ? undefined : priorityFilter as "low" | "medium" | "high" }); const create = trpc.hub.deadlines.create.useMutation({ onSuccess: () => { utils.hub.deadlines.list.invalidate(); utils.hub.dashboard.invalidate(); setOpen(false); toast.success("Deadline added. Future you says thanks."); }, onError: e => toast.error(e.message) }); const updateStatus = trpc.hub.deadlines.setStatus.useMutation({ onSuccess: () => { utils.hub.deadlines.list.invalidate(); utils.hub.dashboard.invalidate(); } });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ title: String(form.get("title")), subject: String(form.get("subject")), description: String(form.get("description") || "") || undefined, dueAt: new Date(`${String(form.get("dueAt"))}T12:00:00`), priority: String(form.get("priority")) as "low" | "medium" | "high" }); };
  return <><PageHeader eyebrow="Keep the important stuff visible" title="Deadline tracker" action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="memphis-button"><Plus className="mr-2 h-4 w-4" />Add deadline</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto border-2 border-black sm:max-w-lg"><DialogHeader><DialogTitle className="font-display text-2xl font-black uppercase">Add a deadline</DialogTitle><DialogDescription>Assignments, exams, presentations — bring them all together.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="Title"><Input name="title" placeholder="Algorithms problem set" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Subject"><Input name="subject" placeholder="Algorithms" required /></Field><Field label="Due date"><Input name="dueAt" type="date" required /></Field></div><Field label="Priority"><NativeSelect name="priority" options={["low", "medium", "high"]} /></Field><Field label="Description"><Textarea name="description" placeholder="Any helpful detail" /></Field><Button className="memphis-button w-full" disabled={create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Save deadline</Button></form></DialogContent></Dialog>} />
    <div className="mb-6 flex flex-wrap items-center gap-3"><div className="inline-flex rounded-xl border-2 border-black bg-white p-1 shadow-[3px_3px_0_#000]"><button onClick={() => setStatus("pending")} className={`rounded-lg px-4 py-2 text-sm font-black ${status === "pending" ? "bg-[#ffe46a]" : ""}`}>To do</button><button onClick={() => setStatus("completed")} className={`rounded-lg px-4 py-2 text-sm font-black ${status === "completed" ? "bg-[#c6f6e7]" : ""}`}>Completed</button></div><div className="w-44"><FilterSelect value={priorityFilter} onChange={setPriorityFilter} placeholder="All priorities" options={["low", "medium", "high"]} /></div></div>
    {list.error ? <QueryError message={list.error.message} /> : list.isLoading ? <LoadingState /> : list.data?.length ? <div className="space-y-3">{list.data.map(item => <article key={item.id} className={`flex flex-col gap-4 rounded-2xl border-2 border-black p-5 shadow-[4px_4px_0_#000] sm:flex-row sm:items-center ${item.status === "completed" ? "bg-[#c6f6e7]" : "bg-white"}`}><button aria-label={`Mark ${item.title} as ${item.status === "pending" ? "completed" : "pending"}`} onClick={() => updateStatus.mutate({ deadlineId: item.id, status: item.status === "pending" ? "completed" : "pending" })} className={`grid h-8 w-8 shrink-0 place-items-center rounded-full border-2 border-black ${item.status === "completed" ? "bg-black text-white" : "bg-white"}`}>{item.status === "completed" && <Check className="h-4 w-4" />}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className={`font-display text-xl font-black uppercase ${item.status === "completed" ? "line-through" : ""}`}>{item.title}</h2><Badge className="border-2 border-black bg-white text-[10px] font-black uppercase text-black">{item.priority}</Badge></div><p className="mt-1 text-sm font-bold text-black/65">{item.subject} · due {formatDate(item.dueAt)}</p>{item.description && <p className="mt-2 text-sm font-medium text-black/70">{item.description}</p>}</div></article>)}</div> : <EmptyState title={status === "pending" ? "Nothing due yet" : "Nothing completed yet"} text={status === "pending" ? "Add an assignment or exam deadline to get started." : "Complete an item and it will live here."} icon={LayoutList} />}</>;
}

function LostFoundView() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const [query, setQuery] = useState(""); const [postType, setPostType] = useState("all"); const [category, setCategory] = useState("all"); const [open, setOpen] = useState(false); const list = trpc.hub.lostFound.list.useQuery({ query: query || undefined, postType: postType === "all" ? undefined : postType as "lost" | "found", category: category === "all" ? undefined : category }); const create = trpc.hub.lostFound.create.useMutation({ onSuccess: () => { utils.hub.lostFound.list.invalidate(); setOpen(false); toast.success("Your post is now on the board."); }, onError: e => toast.error(e.message) }); const resolve = trpc.hub.lostFound.setResolved.useMutation({ onSuccess: () => utils.hub.lostFound.list.invalidate() });
  const categories = Array.from(new Set((list.data ?? []).map(post => post.category))); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ postType: String(form.get("postType")) as "lost" | "found", title: String(form.get("title")), category: String(form.get("category")), description: String(form.get("description")), location: String(form.get("location")), contactInfo: String(form.get("contactInfo")) }); };
  return <><PageHeader eyebrow="Campus kindness, made visible" title="Lost & found" action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="memphis-button"><Plus className="mr-2 h-4 w-4" />Post an item</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto border-2 border-black sm:max-w-lg"><DialogHeader><DialogTitle className="font-display text-2xl font-black uppercase">Post to the board</DialogTitle><DialogDescription>Provide enough detail for the right person to recognize the item and contact you.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Post type"><NativeSelect name="postType" options={["lost", "found"]} /></Field><Field label="Category"><Input name="category" placeholder="Keys, bag, card" required /></Field></div><Field label="Title"><Input name="title" placeholder="Black wireless earbud case" required /></Field><Field label="Description"><Textarea name="description" placeholder="Colour, markings, or helpful details" required /></Field><Field label="Location"><Input name="location" placeholder="Library, second floor" required /></Field><Field label="Contact information"><Input name="contactInfo" placeholder="Email or phone number" required /></Field><Button className="memphis-button w-full" disabled={create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Publish post</Button></form></DialogContent></Dialog>} />
    <div className="mb-6 grid gap-3 rounded-2xl border-2 border-black bg-white p-4 shadow-[4px_4px_0_#000] md:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4" /><Input value={query} onChange={e => setQuery(e.target.value)} className="pl-9" placeholder="Search item, description, or location" /></div><FilterSelect value={postType} onChange={setPostType} placeholder="All posts" options={["lost", "found"]} /><FilterSelect value={category} onChange={setCategory} placeholder="All categories" options={categories} /></div>
    {list.error ? <QueryError message={list.error.message} /> : list.isLoading ? <LoadingState /> : list.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.data.map(post => <article key={post.id} className={`rounded-2xl border-2 border-black p-5 shadow-[4px_4px_0_#000] ${post.postType === "lost" ? "bg-[#fff7ef]" : "bg-[#c6f6e7]"}`}><div className="flex items-start justify-between gap-3"><Badge className="border-2 border-black bg-white text-[10px] font-black uppercase text-black">{post.postType}</Badge>{post.isResolved && <Badge className="border-2 border-black bg-[#ffe46a] text-[10px] font-black uppercase text-black">Resolved</Badge>}</div><h2 className="mt-5 font-display text-xl font-black uppercase leading-none">{post.title}</h2><p className="mt-2 text-xs font-black uppercase tracking-wide text-[#6046a6]">{post.category}</p><p className="mt-3 text-sm font-medium leading-5 text-black/75">{post.description}</p><div className="mt-5 space-y-2 border-t-2 border-black pt-4 text-sm font-bold"><p className="flex items-center gap-2"><MapPin className="h-4 w-4" />{post.location}</p><p className="flex items-center gap-2"><Handshake className="h-4 w-4" />{post.contactInfo}</p></div>{post.userId === user?.id && <Button variant="outline" onClick={() => resolve.mutate({ postId: post.id, isResolved: !post.isResolved })} className="mt-4 border-2 border-black bg-white font-black">Mark as {post.isResolved ? "active" : "resolved"}</Button>}</article>)}</div> : <EmptyState title="No items found" text="Try a broader search or post the first item to the community board." icon={PackageSearch} />}</>;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-black"><span>{label}</span>{children}</label>; }
function NativeSelect({ name, options }: { name?: string; options: readonly string[] }) { return <select name={name} className="h-10 rounded-md border-2 border-black bg-white px-3 text-sm font-bold outline-none focus:ring-2 focus:ring-[#6046a6]">{options.map(option => <option key={option} value={option}>{option}</option>)}</select>; }
function FilterSelect({ value, onChange, placeholder, options }: { value: string; onChange: (value: string) => void; placeholder: string; options: string[] }) { return <Select value={value} onValueChange={onChange}><SelectTrigger className="border-2 border-black bg-white font-bold"><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent>{["all", ...options].map(option => <SelectItem key={option} value={option}>{option === "all" ? placeholder : option}</SelectItem>)}</SelectContent></Select>; }
function LoadingState() { return <div className="grid min-h-48 place-items-center rounded-2xl border-2 border-dashed border-black bg-white/60"><Loader2 className="h-7 w-7 animate-spin" /></div>; }
function QueryError({ message }: { message: string }) { return <div className="rounded-2xl border-2 border-black bg-[#ffc6ad] p-6 shadow-[4px_4px_0_#000]"><h2 className="font-display text-2xl font-black uppercase">A small hiccup</h2><p className="mt-2 font-medium">{message}</p><Button onClick={() => window.location.reload()} className="memphis-button mt-5">Try again</Button></div>; }

export default function Dashboard() {
  const { user, loading, isAuthenticated, logout } = useAuth(); const [location, setLocation] = useLocation(); const [menuOpen, setMenuOpen] = useState(false);
  const path = location.replace("/app", "").replace(/^\//, ""); const current = (nav.some(item => item.key === path) ? path : "dashboard") as HubSection; const setSection = (section: HubSection) => { setLocation(section === "dashboard" ? "/app" : `/app/${section}`); setMenuOpen(false); };
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#ffdfcf]"><Loader2 className="h-8 w-8 animate-spin" /></div>;
  if (!isAuthenticated) return <div className="grid min-h-screen place-items-center bg-[#ffdfcf] p-5"><div className="max-w-md rounded-[24px] border-2 border-black bg-white p-8 text-center shadow-[7px_7px_0_#000]"><GraduationCap className="mx-auto h-10 w-10" /><h1 className="mt-5 font-display text-3xl font-black uppercase">Your hub is waiting</h1><p className="mt-3 font-medium text-black/70">Sign in to create a private student workspace.</p><Button onClick={() => startLogin()} className="memphis-button mt-6">Sign in to continue</Button></div></div>;
  return <div className="min-h-screen bg-[#ffdfcf] text-black"><div className="fixed inset-0 pointer-events-none opacity-60 memphis-workspace-pattern" /><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b-2 border-black bg-[#fff7ef]/95 px-4 backdrop-blur md:hidden"><button onClick={() => setMenuOpen(!menuOpen)} className="rounded-lg border-2 border-black bg-white p-2"><Menu className="h-5 w-5" /></button><span className="font-display font-black uppercase">Student hub</span><MemphisMark /></header>
    <div className="relative z-10 mx-auto flex min-h-screen max-w-[1600px]"><aside className={`${menuOpen ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-40 flex w-[280px] flex-col border-r-2 border-black bg-[#fff7ef] p-5 transition-transform duration-200 md:sticky md:top-0 md:h-screen md:translate-x-0`}><div className="mb-9 flex items-center justify-between"><button onClick={() => setSection("dashboard")} className="flex items-center gap-3 text-left"><span className="grid h-11 w-11 place-items-center rounded-[14px] border-2 border-black bg-[#c6f6e7] font-black shadow-[3px_3px_0_#000]">S</span><span className="font-display text-base font-black uppercase leading-none">Student<br />Survival Hub</span></button><button className="md:hidden" onClick={() => setMenuOpen(false)}><X className="h-5 w-5" /></button></div><nav className="space-y-1">{nav.map(item => { const Icon = item.icon; const active = current === item.key; return <button key={item.key} onClick={() => setSection(item.key)} className={`flex w-full items-center gap-3 rounded-xl border-2 px-3 py-3 text-left text-sm font-black transition-transform hover:translate-x-1 ${active ? "border-black bg-[#ffe46a] shadow-[3px_3px_0_#000]" : "border-transparent hover:border-black hover:bg-white"}`}><Icon className="h-5 w-5" />{item.label}</button>; })}</nav><div className="mt-auto rounded-2xl border-2 border-black bg-white p-3"><div className="flex items-center gap-3"><Avatar className="border-2 border-black"><AvatarFallback className="bg-[#e8ddff] font-black">{user?.name?.[0] ?? "S"}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-sm font-black">{user?.name ?? "Student"}</p><p className="truncate text-xs font-semibold text-black/55">Your study space</p></div></div><button onClick={logout} className="mt-3 flex w-full items-center gap-2 border-t-2 border-black pt-3 text-xs font-black uppercase text-black/65 hover:text-black"><LogOut className="h-4 w-4" />Sign out</button></div></aside>{menuOpen && <button className="fixed inset-0 z-30 bg-black/25 md:hidden" aria-label="Close menu" onClick={() => setMenuOpen(false)} />}
      <main className="min-w-0 flex-1 px-5 py-8 md:px-9 md:py-10 xl:px-14">{current === "dashboard" && <DashboardView setSection={setSection} />}{current === "profile" && <ProfileView />}{current === "notes" && <NotesView />}{current === "groups" && <GroupsView />}{current === "timetable" && <TimetableView />}{current === "deadlines" && <DeadlinesView />}{current === "lost-found" && <LostFoundView />}</main></div></div>;
}
